### ISSUE TITLE
You can access the Archives through the Town Hall before the Archives are built

### ISSUE THREAD

**Issue by dginovker** [seiyria/Rasterkhann#29]
**Describe the bug**
Before purchasing Level 1 Archives, you can click on the Town Hall and access the Archives on the right.

(It's possible this is a feature, and Level 1 Archives don't do anything but put it on the map)

**To Reproduce**
1. Don't have Archives (have them "level 0" but build-able)
2. Click Town Hall
3. Click Archives

**Expected behavior**
Town Hall should not show archives when the archives are not built

**Screenshots**
I just built archives, but you can see it here while the archives still aren't built
![image](https://user-images.githubusercontent.com/32943174/87351089-e33bd600-c526-11ea-92e5-ab663bc16582.png)

**Platform (please complete the following information):**
 - OS: Web, Linux
 - Browser Brave

**Additional context**
I noticed there was an update released since I bought the archives. If you already fixed it, then close the issue (but this was a bug as of a few hours ago)

**Comment by seiyria** [comment]
Thanks for the detailed report! I know exactly what's causing this and I'll fix it right away.
