### ISSUE TITLE
No Weapons in the Bazaar

### ISSUE THREAD

**Issue by cpyle0819** [seiyria/Rasterkhann#73]
**Describe the bug**
The bazaar is empty of items upon building.

**To Reproduce**
1. Build Bazaar
2. Open Bazaar

**Expected behavior**
Bazaar should have items.

**Screenshots**
![Screen Shot 2020-07-27 at 11 10 04 AM](https://user-images.githubusercontent.com/2723491/88558708-e4c2cf00-cff9-11ea-90de-bc63eb173023.png)

**Platform (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser: Chrome

**Additional context**

**Comment by seiyria** [comment]
It's possible that you don't have an armory built, or the armory hasn't produced any items for you yet. I will update the help text to reflect that you need the Alchemist and the Armory to get items.

**Comment by cpyle0819** [comment]
I sure don't. Thanks! That will be a good update.
